<!-- Nije dobra praksa tek tako bilo gdje u view ići u JS -->
<script>
    document.writeln('Hello');
</script>


<a href="#" onclick="primjeAJAXcisti();">AJAX poziv 1</a>


<a href="#" id="ajax2">AJAX poziv 2</a>

<a href="#" id="ajax3">AJAX poziv 3</a>

<a href="#" id="jQuery1">jQuery 1</a>

<a href="#" id="jQuery2">jQuery 2</a>

<div id='panel1'>

</div>


<ol id="lista">
    <li> Osijek </li>
    <li> Zagreb </li>
    <li> Donji Miholjac </li>
    <li> Valpovo </li>
</ol>