<form action="" method="post">
    <fieldset class="fieldset">
        <legend><?=$legend?></legend>

        <?php 
        echo App::inputText('ime',$e->ime);
        echo App::inputText('prezime',$e->prezime);
        echo App::inputText('email',$e->email);
        echo App::inputText('oib',$e->oib);
        echo App::inputText('brojugovora',$e->brojugovora);
        ?>

        <hr>
        <?=$poruka?>

        <div class="grid-x grid-padding-x">
            <div class="large-6 cell">
                <a href="<?=App::config('url')?>polaznik/index"
                class="button alert expanded">Odustani</a>
            </div>
            <div class="large-6 cell">
                <input type="submit" class="button success expanded" 
                value="<?=$akcija?>">
            </div>
        </div>
        
        

    </fieldset>
</form>