<a href="<?=App::config('url')?>polaznik/novi" 
class="success button expanded">
    Dodaj novog polaznika
</a>

<form action="" method="get">
    <input type="text" name="uvjet" id="uvjet"
    placeholder="dio imena, prezimena ili OIB-a"
    value="<?=$uvjet?>" >
</form>
<?php include 'stranicenje.phtml' ?>
<div class="grid-x grid-padding-x">
    <?php foreach($podaci as $red): ?>
        <div class="large-3 medium-6 small-12 cell">
            <div class="callout">
                <img 
                class="slika" id="p_<?=$red->sifra?>"
                src="<?=$red->slika?>" 
                alt="<?=$red->ime?> <?=$red->prezime?>">

                <p><?=$red->ime?> <?=$red->prezime?></h1><hr>
                <?php
                $par=['polaznik', $red->ime . ' ' . $red->prezime, $red->clan==0];
                include BP_APP . 'view/includes/promjenabrisanje.phtml';
                ?>
            </div>
        </div>
    <?php endforeach;?>
</div>


<?php include 'stranicenje.phtml' ?>



<div class="reveal" id="slikaModal" data-reveal>
    <div style="max-height: 300px; overflow: auto;">
        <img id="image" src="" alt="" />
    </div>
  
  <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
  <a href="#" id="spremi">Spremi</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>