<a href="<?=App::config('url')?>smjer/novi" class="success button expanded">
    Dodaj novi smjer
</a>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Cijena (€)</th>
            <th>Upisnina (€)</th>
            <th>Trajanje (sati)</th>
            <th>Certificiran</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td>
                    <span title="<?=$red->title?>">
                        <?=$red->naziv?>
                    </span>
                    </td>
                <td><?=$red->cijena?></td>
                <td><?=$red->upisnina?></td>
                <td><?=$red->trajanje?></td>
                <td><i class="fi-<?=$red->certificiran?>"></i></td>
                <td>
                <a href="<?=App::config('url')?>smjer/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>    
                <a href=""><i class="fi-trash"></i></a>
            </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>