<a href="<?=App::config('url')?>smjer/novi" class="success button expanded">
    Dodaj novi smjer
</a>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Cijena (€)</th>
            <th>Upisnina (€)</th>
            <th>Trajanje (sati)</th>
            <th>Certificiran</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td>
                    <span title="<?=$red->title?>" id="s_<?=$red->sifra?>" class="nazivSmjera">
                        <?=$red->naziv?>
                    </span>
                    </td>
                <td><?=$red->cijena?></td>
                <td><?=$red->upisnina?></td>
                <td><?=$red->trajanje?></td>
                <td><i class="fi-<?=$red->certificiran?>"></i></td>
                <td>
                <a href="<?=App::config('url')?>smjer/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>    
                <?php if($red->grupa==0): ?>
                    <a onclick="return confirm('Sigurno obrisati smjer <?=$red->naziv?>?');"
                    href="<?=App::config('url')?>smjer/brisanje/<?=$red->sifra?>"><i class="fi-trash"></i></a>
                <?php else: ?>
                    <i title="Smjer se ne može obrisati jer ima grupa" 
                    class="fi-trash" style="color: gray"></i>
                <?php endif; ?>

            </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?=$poruka?>