<form action="" method="post">
    <fieldset>
        <legend>Unos novog smjera</legend>

        <label 
        <?php if(isset($poruke['naziv'])): ?>
            class="is-invalid-label greska" 
        <?php endif; ?>
        for="naziv">Naziv</label>
        <input 
        <?php if(isset($poruke['naziv'])): ?>
            class="is-invalid-input"
        <?php endif; ?>
         type="text" id="naziv" name="naziv"
        value="<?=$e->naziv?>">

        <?php if(isset($poruke['naziv'])): ?>
            <span class="form-error is-visible">
            <?=$poruke['naziv'] ?>
        </span>
        <?php endif; ?>
       

        <label 
        <?php if(isset($poruke['cijena'])): ?>
            class="is-invalid-label greska" 
        <?php endif; ?>
        for="cijena">Cijena</label>
        <input 
        <?php if(isset($poruke['cijena'])): ?>
            class="is-invalid-input"
        <?php endif; ?>
        type="text" id="cijena" name="cijena"
        value="<?=$e->cijena?>">
        <?php if(isset($poruke['cijena'])): ?>
            <span class="form-error is-visible">
            <?=$poruke['cijena'] ?>
        </span>
        <?php endif; ?>

        <label for="upisnina">Upisnina</label>
        <input type="text" id="upisnina" name="upisnina"
        value="<?=$e->upisnina?>">

        <label
        <?php if(isset($poruke['trajanje'])): ?>
            class="is-invalid-label greska" 
        <?php endif; ?>
        for="trajanje">Trajanje</label>
        <input 
        <?php if(isset($poruke['trajanje'])): ?>
            class="is-invalid-input"
        <?php endif; ?>
        type="text" id="trajanje" name="trajanje"
        value="<?=$e->trajanje?>">
        <?php if(isset($poruke['trajanje'])): ?>
            <span class="form-error is-visible">
            <?=$poruke['trajanje'] ?>
        </span>
        <?php endif; ?>

        Certificiran<br>
        <input type="radio" name="certificiran" id="da" value="true"
        <?php if($e->certificiran) echo 'checked="checked"'; ?>>
        <label for="da">DA</label>
        
        <input type="radio" name="certificiran" id="ne" value="false"
        <?php if(!$e->certificiran) echo 'checked="checked"'; ?>>
        <label for="ne">NE</label>

        <hr>

        <div class="grid-x grid-padding-x">
            <div class="large-6 cell">
                <a href="<?=App::config('url')?>smjer/index"
                class="button alert expanded">Odustani</a>
            </div>
            <div class="large-6 cell">
                <input type="submit" class="button success expanded" 
                value="Dodaj"  style="margin-top: 0px">
            </div>
        </div>
        
        

    </fieldset>
</form>