<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=App::config('nazivApp');?></title>
<link rel="stylesheet" href="<?=App::config('url')?>public/css/foundation.css">
<link rel="stylesheet" href="<?=App::config('url')?>public/css/app.css">

<?php /* https://css-tricks.com/essential-meta-tags-social-media/ */?>
<!--  Essential META Tags -->
<meta property="og:title" content="<?=App::config('nazivApp');?>">
<meta property="og:type" content="article" />
<meta property="og:image" content="<?=App::config('url')?>public/img/thumbnail.jpg">
<meta property="og:url" content="<?=App::config('url')?>">
<meta name="twitter:card" content="summary_large_image">

<!--  Non-Essential, But Recommended -->
<meta property="og:description" content="<?=App::config('nazivApp');?>">
<meta property="og:site_name" content="<?=App::config('nazivApp');?>">
<meta name="twitter:image:alt" content="<?=App::config('nazivApp');?>">

