<a href="<?=App::config('url')?><?=$par[0]?>/promjena/<?=$red->sifra?>">
<i class="fi-pencil"></i></a>    
<?php if($par[2]): ?>
    <a 
    onclick="return confirm('Sigurno obrisati <?=$par[1]?>?');"
    href="<?=App::config('url')?><?=$par[0]?>/brisanje/<?=$red->sifra?>">
    <i class="fi-trash"></i></a>
<?php else: ?>
    <i title="<?=$par[0]?> se ne može obrisati" 
    class="fi-trash" style="color: gray"></i>
<?php endif; ?>