<a href="<?=App::config('url')?>grupa/novi" class="success button expanded">
    Dodaj novu grupu
</a>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Smjer</th>
            <th>Predavač</th>
            <th>Datum početka</th>
            <th>Maksimalno polaznika</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($podaci as $red): ?>
            <tr>
                <td>
                        <?=$red->naziv?>
                        <div title="Klik za kopiranje u međuspremnik" class="callout polaznici"
                        style="cursor: pointer;">
                <?php 
                $s='';
                foreach($red->polaznici as $p){
                    $s .= $p->ime . ' ' . $p->prezime . ',';
                }
                if($s!==''){
                    echo substr($s,0,strlen($s)-1);
                }
                ?>
            </div>
                    </td>
                <td><?=$red->smjer?></td>
                <td><?=$red->predavac?></td>
                <td><?=$red->datumpocetka?></td>
                <td><?=$red->maksimalnopolaznika?></td>
                <td>
                <a href="<?=App::config('url')?>grupa/promjena/<?=$red->sifra?>"><i class="fi-pencil"></i></a>    
                <?php if($red->polaznika==0): ?>
                    <a onclick="return confirm('Sigurno obrisati grupu <?=$red->naziv?>?');"
                    href="<?=App::config('url')?>grupa/brisanje/<?=$red->sifra?>"><i class="fi-trash"></i></a>
                <?php else: ?>
                    <i title="Grupa se ne može obrisati jer ima polaznike" 
                    class="fi-trash" style="color: gray"></i>
                <?php endif; ?>

            </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>

